"""Reviewed public Python surface contract."""

from __future__ import annotations

import os
import subprocess
import sys

APPROVED: dict[str, frozenset[str]] = {
    "talktoharnesses": frozenset({"__version__"}),
    "talktoharnesses.client": frozenset(
        {
            "APIError",
            "AsyncTalkToHarnessesClient",
            "ConversationStreamItem",
        }
    ),
    "talktoharnesses.application": frozenset(
        {
            "CommittedEventBroker",
            "CommittedEventPublisher",
            "ConversationWakeup",
            "Persistence",
            "StreamingTextRedactor",
            "TalkToHarnessesService",
        }
    ),
    "talktoharnesses.providers": frozenset(
        {
            "AdapterRegistry",
            "HarnessAdapter",
            "HarnessInteractionRequest",
            "HarnessSession",
            "ResumeSessionRequest",
            "StartSessionRequest",
            "SteerRequest",
            "TurnRequest",
        }
    ),
    "talktoharnesses.runtime": frozenset(
        {
            "ManagedRuntime",
            "ProcessEvent",
            "ProcessExitedEvent",
            "ProcessForcedTerminationEvent",
            "ProcessSilenceWarningEvent",
            "ProcessStartedEvent",
            "ProcessStderrTruncatedEvent",
            "RuntimeManager",
            "RuntimePolicy",
        }
    ),
    "talktoharnesses.django": frozenset({"DjangoPersistence"}),
    "talktoharnesses.domain": frozenset(
        {
            "ActivityProjection",
            "ActivityStatus",
            "ApprovalAction",
            "ApprovalDecision",
            "ApprovalMatcher",
            "ApprovalRequestPayload",
            "ApprovalRule",
            "ApprovalRuleDecision",
            "ApprovalRuleInput",
            "ApprovalRuleProjection",
            "ApprovalRuleScope",
            "ApprovalRuleScopeKind",
            "BackgroundActivity",
            "BlanketNetworkMatcher",
            "CanonicalToolResult",
            "Command",
            "CommandApprovalAction",
            "CommandKind",
            "CommandProjection",
            "CommandStatus",
            "Conversation",
            "ConversationDetail",
            "ConversationEvent",
            "ConversationHarnessBinding",
            "ConversationRuleScope",
            "ConversationSearchHit",
            "ConversationShell",
            "ConversationSnapshot",
            "ConversationState",
            "ConversationStatus",
            "DomainError",
            "ErrorCode",
            "ErrorProjection",
            "EventPayload",
            "ExactArgvMatcher",
            "ExactPathMatcher",
            "ExecutableRuleScope",
            "ExpectedEvent",
            "FileApprovalAction",
            "FileChange",
            "FileOperation",
            "HarnessCapabilities",
            "HarnessConfiguration",
            "HarnessEffortInfo",
            "HarnessEvent",
            "HarnessInstance",
            "HarnessInstanceRuleScope",
            "HarnessKind",
            "HarnessMcpHeader",
            "HarnessMcpServer",
            "HarnessModeInfo",
            "HarnessModelInfo",
            "HarnessProbeProjection",
            "HarnessProjection",
            "InteractionAnswer",
            "InteractionAuditProjection",
            "InteractionKind",
            "InteractionMatchContext",
            "InteractionProjection",
            "InteractionResolutionResult",
            "InteractionStatus",
            "LaunchSnapshot",
            "MatchDecision",
            "Message",
            "MessageChunk",
            "MessageProjection",
            "MessageRole",
            "NativeIORecord",
            "NetworkApprovalAction",
            "Page",
            "PendingInteraction",
            "Plan",
            "PlanItem",
            "PlanProjection",
            "PrincipalGlobalRuleScope",
            "ProcessRecord",
            "ProcessStatus",
            "ReadinessProjection",
            "ReasoningBlock",
            "RecursiveDirectoryMatcher",
            "RetentionPolicyProjection",
            "RetentionPreviewProjection",
            "SearchSnippet",
            "SubmitTurnResult",
            "SyncProjection",
            "TokenProjection",
            "ToolOutcome",
            "ToolOutputChunk",
            "ToolProjection",
            "TranscriptDocument",
            "TranscriptFixture",
            "TranscriptMessage",
            "TranscriptTool",
            "TranscriptTurn",
            "TransitionResult",
            "Turn",
            "TurnProjection",
            "TurnStatus",
            "UsageRecord",
            "UserRuleScope",
            "VersionAdvisory",
            "append_events",
            "apply_native_title",
            "apply_steer",
            "archive_conversation",
            "assert_redaction",
            "cancel_interaction",
            "cancel_open_interactions",
            "cancel_queued_prompt",
            "change_mode",
            "close_session",
            "commit_switch",
            "complete_activity",
            "complete_turn",
            "conversation_event_adapter",
            "dump_transcript_document",
            "dump_transcript_fixture",
            "edit_queued_prompt",
            "event_payload_adapter",
            "fail_running_activities",
            "fail_session",
            "fail_switch",
            "fail_turn",
            "fixture_to_dict",
            "interrupt_turn",
            "load_transcript_document",
            "load_transcript_fixture",
            "mark_outcome_unknown",
            "mark_requires_recreation",
            "matcher_matches",
            "new_conversation_state",
            "normalize_approval_action",
            "normalize_approval_path",
            "normalize_approval_rule",
            "normalize_directory",
            "path_is_under_directory",
            "pin_conversation",
            "reap_session",
            "register_activity",
            "remember_native_ids",
            "request_interaction",
            "resume_session",
            "rotate_session",
            "rule_matches_request",
            "scope_applies",
            "select_matching_rule",
            "set_retention_exemption",
            "snooze_conversation",
            "soft_delete_conversation",
            "start_session",
            "start_turn",
            "submit_interaction_answer",
            "submit_turn",
            "unarchive_conversation",
            "unpin_conversation",
            "unsnooze_conversation",
            "update_interaction_draft",
        }
    ),
}


def test_core_public_imports_in_fresh_interpreter() -> None:
    code = """
import sys
import talktoharnesses
import talktoharnesses.domain
import talktoharnesses.application
import talktoharnesses.providers
import talktoharnesses.runtime

assert talktoharnesses.__all__ == ["__version__"]
assert "django" not in sys.modules
assert "TalkToHarnessesService" in talktoharnesses.application.__all__
"""
    result = subprocess.run(
        [sys.executable, "-c", code],
        check=False,
        capture_output=True,
        text=True,
        env=os.environ.copy(),
    )
    assert result.returncode == 0, result.stdout + result.stderr
