"""Vendored Codex app-server schemas and the Pydantic models generated from them.

``models.py`` is machine-generated by ``scripts/generate_codex_models.py`` from
the JSON schemas in ``schemas/``, pinned to the commit in ``schemas/UPSTREAM_REF``.
Do not edit it by hand — regenerate instead.

The driver speaks dict payloads on the wire (so an upstream field addition
degrades rather than raising), and ``tests/test_codex_schema_drift.py`` checks
the method-name constants and item-type mapping against these schemas so drift
surfaces as a failing test rather than as silently dropped events.
"""
