# Generated by Django 5.2.17 on 2026-08-15 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_SEARCH_TABLE = "talktoharnesses_search_document"
_SEARCH_FTS = "talktoharnesses_search_document_fts"

_POSTGRES_SEARCH_FORWARD = (
    f"ALTER TABLE {_SEARCH_TABLE} ADD COLUMN search_vector tsvector GENERATED ALWAYS AS "
    "(to_tsvector('simple', coalesce(normalized_text, ''))) STORED",
    f"CREATE INDEX tth_search_vector_gin ON {_SEARCH_TABLE} USING GIN (search_vector)",
)
_POSTGRES_SEARCH_REVERSE = (
    "DROP INDEX IF EXISTS tth_search_vector_gin",
    f"ALTER TABLE {_SEARCH_TABLE} DROP COLUMN IF EXISTS search_vector",
)
_SQLITE_SEARCH_FORWARD = (
    f"CREATE VIRTUAL TABLE {_SEARCH_FTS} USING fts5("
    f"conversation_id UNINDEXED, normalized_text, content='{_SEARCH_TABLE}', "
    "tokenize='unicode61 remove_diacritics 0')",
    f"""CREATE TRIGGER {_SEARCH_FTS}_ai AFTER INSERT ON {_SEARCH_TABLE} BEGIN
        INSERT INTO {_SEARCH_FTS}(rowid, conversation_id, normalized_text)
        VALUES (new.rowid, new.conversation_id, new.normalized_text);
    END""",
    f"""CREATE TRIGGER {_SEARCH_FTS}_ad AFTER DELETE ON {_SEARCH_TABLE} BEGIN
        INSERT INTO {_SEARCH_FTS}({_SEARCH_FTS}, rowid, conversation_id, normalized_text)
        VALUES ('delete', old.rowid, old.conversation_id, old.normalized_text);
    END""",
    f"""CREATE TRIGGER {_SEARCH_FTS}_au AFTER UPDATE ON {_SEARCH_TABLE} BEGIN
        INSERT INTO {_SEARCH_FTS}({_SEARCH_FTS}, rowid, conversation_id, normalized_text)
        VALUES ('delete', old.rowid, old.conversation_id, old.normalized_text);
        INSERT INTO {_SEARCH_FTS}(rowid, conversation_id, normalized_text)
        VALUES (new.rowid, new.conversation_id, new.normalized_text);
    END""",
    f"INSERT INTO {_SEARCH_FTS}({_SEARCH_FTS}) VALUES('rebuild')",
)
_SQLITE_SEARCH_REVERSE = (
    f"DROP TRIGGER IF EXISTS {_SEARCH_FTS}_au",
    f"DROP TRIGGER IF EXISTS {_SEARCH_FTS}_ad",
    f"DROP TRIGGER IF EXISTS {_SEARCH_FTS}_ai",
    f"DROP TABLE IF EXISTS {_SEARCH_FTS}",
)


def _execute(schema_editor, statements):
    for statement in statements:
        schema_editor.execute(statement)


def create_search_index(apps, schema_editor):
    del apps
    statements = (
        _POSTGRES_SEARCH_FORWARD
        if schema_editor.connection.vendor == "postgresql"
        else _SQLITE_SEARCH_FORWARD
    )
    _execute(schema_editor, statements)


def drop_search_index(apps, schema_editor):
    del apps
    statements = (
        _POSTGRES_SEARCH_REVERSE
        if schema_editor.connection.vendor == "postgresql"
        else _SQLITE_SEARCH_REVERSE
    )
    _execute(schema_editor, statements)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "activity_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("parent_turn_id", models.UUIDField()),
                ("parent_activity_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, max_length=512, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_activity",
            },
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="talktoharnesses_api_token",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("jti_digest", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "talktoharnesses_api_token",
            },
        ),
        migrations.CreateModel(
            name="CommandRecord",
            fields=[
                ("command_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("worker_id", models.CharField(blank=True, max_length=255, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField()),
                ("target_turn_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_command",
            },
        ),
        migrations.CreateModel(
            name="ConversationAggregate",
            fields=[
                (
                    "conversation_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("owner_id", models.CharField(db_index=True, max_length=255)),
                ("version", models.PositiveBigIntegerField(default=0)),
                ("next_event_sequence", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(default="", max_length=512)),
                ("status", models.CharField(default="idle", max_length=32)),
                ("harness_kind", models.CharField(blank=True, max_length=32, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("mode", models.CharField(blank=True, max_length=255, null=True)),
                ("has_pending_interactions", models.BooleanField(default=False)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("retention_exempt", models.BooleanField(default=False)),
                ("latest_activity_at", models.DateTimeField(blank=True, null=True)),
                ("runtime_worker_id", models.CharField(blank=True, max_length=255, null=True)),
                ("runtime_lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("runtime_fence", models.PositiveBigIntegerField(default=0)),
                ("state", models.JSONField()),
            ],
            options={
                "db_table": "talktoharnesses_conversation",
            },
        ),
        migrations.CreateModel(
            name="ConversationBindingRecord",
            fields=[
                ("binding_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=32)),
                ("configuration", models.JSONField()),
                ("harness_instance_id", models.UUIDField(blank=True, null=True)),
                ("native_session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("launch_snapshot", models.JSONField(blank=True, null=True)),
                ("requires_session_recreation", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_binding",
            },
        ),
        migrations.CreateModel(
            name="ConversationEventRecord",
            fields=[
                ("event_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("sequence", models.PositiveBigIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("type", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("turn_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_event",
                "ordering": ("conversation_id", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="HarnessRecord",
            fields=[
                ("harness_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("owner_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=32)),
                ("configuration", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("last_probe", models.JSONField(blank=True, null=True)),
                ("last_probed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_harness",
            },
        ),
        migrations.CreateModel(
            name="InteractionAnswerRecord",
            fields=[
                (
                    "interaction_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_event_sequence",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("answer_command_suppressed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "talktoharnesses_interaction_answer",
            },
        ),
        migrations.CreateModel(
            name="InteractionAuditRecord",
            fields=[
                ("audit_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("principal_id", models.CharField(max_length=255)),
                ("interaction_id", models.UUIDField()),
                ("conversation_id", models.UUIDField()),
                ("turn_id", models.UUIDField()),
                ("kind", models.CharField(max_length=32)),
                ("decision", models.CharField(blank=True, max_length=32, null=True)),
                ("answers", models.JSONField(blank=True, null=True)),
                ("automatic", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("provider_kind", models.CharField(blank=True, max_length=32, null=True)),
                ("provider_request_ids", models.JSONField(default=dict)),
                ("deciding_rule_id_copy", models.UUIDField(blank=True, null=True)),
                ("rule_decision", models.CharField(blank=True, max_length=16, null=True)),
                ("rule_scope", models.JSONField(blank=True, null=True)),
                ("rule_matcher", models.JSONField(blank=True, null=True)),
                ("request_action", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_interaction_audit",
            },
        ),
        migrations.CreateModel(
            name="InteractionRecord",
            fields=[
                (
                    "interaction_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("turn_id", models.UUIDField()),
                ("kind", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                ("request", models.JSONField()),
                ("draft", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("provider_correlation", models.JSONField(blank=True, null=True)),
                ("request_event_sequence", models.PositiveBigIntegerField(blank=True, null=True)),
                ("policy_evaluated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_interaction",
            },
        ),
        migrations.CreateModel(
            name="RuntimeProcess",
            fields=[
                ("process_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("binding_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(max_length=16)),
                ("pid", models.BigIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("orphaned_at", models.DateTimeField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("redacted_stderr_tail", models.TextField(default="")),
            ],
            options={
                "db_table": "talktoharnesses_process",
            },
        ),
        migrations.CreateModel(
            name="MessageRecord",
            fields=[
                ("message_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=16)),
                ("text", models.TextField(default="")),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("interrupted", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("order_index", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "db_table": "talktoharnesses_message",
            },
        ),
        migrations.CreateModel(
            name="PlanRecord",
            fields=[
                ("plan_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("items", models.JSONField(default=list)),
                ("order_index", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "talktoharnesses_plan",
            },
        ),
        migrations.CreateModel(
            name="ReasoningRecord",
            fields=[
                (
                    "reasoning_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("text", models.TextField(default="")),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "talktoharnesses_reasoning",
            },
        ),
        migrations.CreateModel(
            name="RecoveryAttemptRecord",
            fields=[
                ("attempt_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("binding_id", models.UUIDField()),
                ("command_id", models.UUIDField(blank=True, null=True)),
                ("turn_id", models.UUIDField(blank=True, null=True)),
                ("worker_id", models.CharField(max_length=255)),
                ("fence", models.PositiveBigIntegerField()),
                ("trigger", models.CharField(max_length=32)),
                ("observed_delivery_phase", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=32)),
                ("result", models.CharField(blank=True, max_length=32, null=True)),
                ("reason_code", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_recovery_attempt",
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicyRecord",
            fields=[
                (
                    "owner_id",
                    models.CharField(
                        editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("months", models.PositiveSmallIntegerField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "talktoharnesses_retention_policy",
            },
        ),
        migrations.CreateModel(
            name="ToolRecord",
            fields=[
                ("tool_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(max_length=255)),
                ("arguments", models.JSONField(default=dict)),
                ("outcome", models.CharField(default="unknown", max_length=32)),
                ("exit_status", models.IntegerField(blank=True, null=True)),
                ("paths", models.JSONField(default=list)),
                ("output_tail", models.TextField(default="")),
                ("full_output", models.TextField(blank=True, null=True)),
                ("order_index", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "talktoharnesses_tool",
            },
        ),
        migrations.CreateModel(
            name="TurnRecord",
            fields=[
                ("turn_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=32)),
                ("user_message_id", models.UUIDField(blank=True, null=True)),
                ("command_id", models.UUIDField(blank=True, null=True)),
                ("terminal_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order_index", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "talktoharnesses_turn",
            },
        ),
        migrations.CreateModel(
            name="WorkerLeaseRecord",
            fields=[
                ("slot", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("worker_id", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField()),
                ("heartbeat_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("draining", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "talktoharnesses_worker_lease",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRuleRecord",
            fields=[
                ("rule_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("principal_id", models.CharField(max_length=255)),
                ("decision", models.CharField(max_length=16)),
                ("scope_kind", models.CharField(max_length=32)),
                ("scope", models.JSONField()),
                ("matcher_kind", models.CharField(max_length=32)),
                ("matcher", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "talktoharnesses_approval_rule",
                "indexes": [
                    models.Index(
                        fields=["principal_id", "scope_kind"], name="tth_rule_principal_scope_idx"
                    ),
                    models.Index(
                        fields=["principal_id", "-created_at", "-rule_id"], name="tth_rule_page_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="search",
                        serialize=False,
                        to="talktoharnesses.conversationaggregate",
                    ),
                ),
                ("owner_id", models.CharField(db_index=True, max_length=255)),
                ("normalized_text", models.TextField(default="")),
                ("search_title", models.TextField(default="")),
                ("search_body", models.TextField(default="")),
                ("snippet_text", models.TextField(default="")),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "talktoharnesses_search_document",
            },
        ),
        migrations.AddIndex(
            model_name="conversationaggregate",
            index=models.Index(
                fields=["owner_id", "-updated_at", "-conversation_id"], name="tth_conv_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationaggregate",
            index=models.Index(fields=["owner_id", "deleted_at"], name="tth_conv_owner_del_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationaggregate",
            index=models.Index(
                fields=["status", "runtime_lease_expires_at"], name="tth_conv_recovery_scan_idx"
            ),
        ),
        migrations.AddField(
            model_name="commandrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="conversationbindingrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="conversationeventrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddIndex(
            model_name="harnessrecord",
            index=models.Index(
                fields=["owner_id", "-created_at", "-harness_id"], name="tth_harness_list_idx"
            ),
        ),
        migrations.AddField(
            model_name="interactionanswerrecord",
            name="command",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interaction_answer",
                to="talktoharnesses.commandrecord",
            ),
        ),
        migrations.AddField(
            model_name="interactionanswerrecord",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interaction_answers",
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="interactionauditrecord",
            name="deciding_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audits",
                to="talktoharnesses.approvalrulerecord",
            ),
        ),
        migrations.AddField(
            model_name="interactionrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.CreateModel(
            name="LaunchHistory",
            fields=[
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="talktoharnesses.runtimeprocess",
                    ),
                ),
                ("launch", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "talktoharnesses_launch_history",
            },
        ),
        migrations.AddField(
            model_name="runtimeprocess",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="messagerecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="reasoningrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="recoveryattemptrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="commandrecord",
            name="recovery_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commands",
                to="talktoharnesses.recoveryattemptrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionpolicyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("months__gte", 1), ("months__lte", 120)),
                name="tth_retention_months_range",
            ),
        ),
        migrations.AddField(
            model_name="toolrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.CreateModel(
            name="UsageRecordRow",
            fields=[
                (
                    "turn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="talktoharnesses.turnrecord",
                    ),
                ),
                ("input_tokens", models.BigIntegerField(blank=True, null=True)),
                ("output_tokens", models.BigIntegerField(blank=True, null=True)),
                ("total_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cached_input_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cost", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "talktoharnesses_usage",
            },
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddField(
            model_name="toolrecord",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talktoharnesses.turnrecord"
            ),
        ),
        migrations.AddField(
            model_name="reasoningrecord",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talktoharnesses.turnrecord"
            ),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talktoharnesses.turnrecord"
            ),
        ),
        migrations.AddField(
            model_name="messagerecord",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talktoharnesses.turnrecord"
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["conversation", "created_at", "activity_id"], name="tth_activity_page_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbindingrecord",
            index=models.Index(
                fields=["conversation", "-created_at"], name="tth_binding_history_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationbindingrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("conversation",),
                name="tth_one_active_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationeventrecord",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="talktoharnesses_unique_event_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionauditrecord",
            index=models.Index(
                fields=["principal_id", "-created_at", "-audit_id"], name="tth_audit_page_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionauditrecord",
            index=models.Index(fields=["interaction_id"], name="tth_audit_interaction_idx"),
        ),
        migrations.AddIndex(
            model_name="interactionrecord",
            index=models.Index(
                fields=["conversation", "created_at", "interaction_id"],
                name="tth_interaction_page_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interactionrecord",
            index=models.Index(
                fields=["status", "policy_evaluated_at"], name="tth_interaction_policy_idx"
            ),
        ),
        migrations.AddField(
            model_name="launchhistory",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryattemptrecord",
            index=models.Index(
                fields=["conversation", "-started_at"], name="tth_recovery_conv_started_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commandrecord",
            constraint=models.UniqueConstraint(
                fields=("conversation", "idempotency_key"),
                name="talktoharnesses_unique_command_key",
            ),
        ),
        migrations.AddField(
            model_name="usagerecordrow",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talktoharnesses.conversationaggregate",
            ),
        ),
        migrations.AddIndex(
            model_name="turnrecord",
            index=models.Index(
                fields=["conversation", "-order_index", "-turn_id"], name="tth_turn_page_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolrecord",
            index=models.Index(
                fields=["conversation", "-order_index", "-tool_id"], name="tth_tool_page_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planrecord",
            index=models.Index(
                fields=["conversation", "-order_index", "-plan_id"], name="tth_plan_page_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecord",
            index=models.Index(
                fields=["conversation", "created_at", "message_id"], name="tth_message_page_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecord",
            index=models.Index(fields=["turn", "sequence"], name="tth_message_turn_idx"),
        ),
        migrations.RunPython(create_search_index, drop_search_index),
    ]
