# Generated by Django 5.2 for talktoharnesses.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationAggregate",
            fields=[
                (
                    "conversation_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("owner_id", models.CharField(db_index=True, max_length=255)),
                ("version", models.PositiveBigIntegerField(default=0)),
                ("next_event_sequence", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("state", models.JSONField()),
            ],
            options={"db_table": "talktoharnesses_conversation"},
        ),
        migrations.CreateModel(
            name="InteractionAnswerRecord",
            fields=[
                (
                    "interaction_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "talktoharnesses_interaction_answer"},
        ),
        migrations.CreateModel(
            name="CommandRecord",
            fields=[
                ("command_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("worker_id", models.CharField(blank=True, max_length=255, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talktoharnesses.conversationaggregate",
                    ),
                ),
            ],
            options={"db_table": "talktoharnesses_command"},
        ),
        migrations.CreateModel(
            name="ConversationEventRecord",
            fields=[
                ("event_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("sequence", models.PositiveBigIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("type", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talktoharnesses.conversationaggregate",
                    ),
                ),
            ],
            options={
                "db_table": "talktoharnesses_event",
                "ordering": ("conversation_id", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="RuntimeProcess",
            fields=[
                ("process_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("binding_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(max_length=16)),
                ("pid", models.BigIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("redacted_stderr_tail", models.TextField(default="")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talktoharnesses.conversationaggregate",
                    ),
                ),
            ],
            options={"db_table": "talktoharnesses_process"},
        ),
        migrations.CreateModel(
            name="LaunchHistory",
            fields=[
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="talktoharnesses.runtimeprocess",
                    ),
                ),
                ("launch", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talktoharnesses.conversationaggregate",
                    ),
                ),
            ],
            options={"db_table": "talktoharnesses_launch_history"},
        ),
        migrations.AddConstraint(
            model_name="conversationeventrecord",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"),
                name="talktoharnesses_unique_event_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="commandrecord",
            constraint=models.UniqueConstraint(
                fields=("conversation", "idempotency_key"),
                name="talktoharnesses_unique_command_key",
            ),
        ),
    ]
