# Generated by Django 5.2.17 on 2026-08-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talktoharnesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('activity_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('parent_turn_id', models.UUIDField()),
                ('parent_activity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talktoharnesses_activity',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='talktoharnesses_api_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('jti_digest', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'talktoharnesses_api_token',
            },
        ),
        migrations.CreateModel(
            name='HarnessRecord',
            fields=[
                ('harness_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=32)),
                ('configuration', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('last_probe', models.JSONField(blank=True, null=True)),
                ('last_probed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talktoharnesses_harness',
            },
        ),
        migrations.CreateModel(
            name='InteractionRecord',
            fields=[
                ('interaction_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('turn_id', models.UUIDField()),
                ('kind', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('request', models.JSONField()),
                ('draft', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'talktoharnesses_interaction',
            },
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('message_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('text', models.TextField(default='')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('interrupted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'talktoharnesses_message',
            },
        ),
        migrations.CreateModel(
            name='PlanRecord',
            fields=[
                ('plan_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('order_index', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'talktoharnesses_plan',
            },
        ),
        migrations.CreateModel(
            name='ReasoningRecord',
            fields=[
                ('reasoning_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'talktoharnesses_reasoning',
            },
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search', serialize=False, to='talktoharnesses.conversationaggregate')),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('normalized_text', models.TextField(default='')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'talktoharnesses_search_document',
            },
        ),
        migrations.CreateModel(
            name='ToolRecord',
            fields=[
                ('tool_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255)),
                ('arguments', models.JSONField(default=dict)),
                ('outcome', models.CharField(default='unknown', max_length=32)),
                ('exit_status', models.IntegerField(blank=True, null=True)),
                ('paths', models.JSONField(default=list)),
                ('output_tail', models.TextField(default='')),
                ('full_output', models.TextField(blank=True, null=True)),
                ('order_index', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'talktoharnesses_tool',
            },
        ),
        migrations.CreateModel(
            name='TurnRecord',
            fields=[
                ('turn_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('user_message_id', models.UUIDField(blank=True, null=True)),
                ('command_id', models.UUIDField(blank=True, null=True)),
                ('terminal_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order_index', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'talktoharnesses_turn',
            },
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='harness_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='has_pending_interactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='latest_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='status',
            field=models.CharField(default='idle', max_length=32),
        ),
        migrations.AddField(
            model_name='conversationaggregate',
            name='title',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddIndex(
            model_name='conversationaggregate',
            index=models.Index(fields=['owner_id', '-updated_at', '-conversation_id'], name='tth_conv_list_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationaggregate',
            index=models.Index(fields=['owner_id', 'deleted_at'], name='tth_conv_owner_del_idx'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddIndex(
            model_name='harnessrecord',
            index=models.Index(fields=['owner_id', '-created_at', '-harness_id'], name='tth_harness_list_idx'),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddField(
            model_name='reasoningrecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddField(
            model_name='toolrecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.CreateModel(
            name='UsageRecordRow',
            fields=[
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='talktoharnesses.turnrecord')),
                ('input_tokens', models.BigIntegerField(blank=True, null=True)),
                ('output_tokens', models.BigIntegerField(blank=True, null=True)),
                ('total_tokens', models.BigIntegerField(blank=True, null=True)),
                ('cached_input_tokens', models.BigIntegerField(blank=True, null=True)),
                ('cost', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'talktoharnesses_usage',
            },
        ),
        migrations.AddField(
            model_name='turnrecord',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddField(
            model_name='toolrecord',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.turnrecord'),
        ),
        migrations.AddField(
            model_name='reasoningrecord',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.turnrecord'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.turnrecord'),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.turnrecord'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['conversation', 'created_at', 'activity_id'], name='tth_activity_page_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['conversation', 'created_at', 'interaction_id'], name='tth_interaction_page_idx'),
        ),
        migrations.AddField(
            model_name='usagerecordrow',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddIndex(
            model_name='turnrecord',
            index=models.Index(fields=['conversation', '-order_index', '-turn_id'], name='tth_turn_page_idx'),
        ),
        migrations.AddIndex(
            model_name='toolrecord',
            index=models.Index(fields=['conversation', '-order_index', '-tool_id'], name='tth_tool_page_idx'),
        ),
        migrations.AddIndex(
            model_name='planrecord',
            index=models.Index(fields=['conversation', '-order_index', '-plan_id'], name='tth_plan_page_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecord',
            index=models.Index(fields=['conversation', 'created_at', 'message_id'], name='tth_message_page_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecord',
            index=models.Index(fields=['turn', 'sequence'], name='tth_message_turn_idx'),
        ),
    ]
