# Generated by Django 5.2.17 on 2026-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talktoharnesses', '0002_usagerecordrow_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxRecord',
            fields=[
                ('kind', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('container_name', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=255)),
                ('host_port', models.PositiveIntegerField()),
                ('base_url', models.CharField(max_length=255)),
                ('split_token', models.CharField(max_length=128)),
                ('status', models.CharField(default='preparing', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_ready_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talktoharnesses_sandbox',
            },
        ),
    ]
