# Generated by Django 5.2.17 on 2026-08-08 17:39

import django.db.models.deletion
from django.db import migrations, models
from typing import Any, cast


def backfill_harness_instance_ids(apps: Any, _schema_editor: Any) -> None:
    ConversationAggregate: Any = apps.get_model('talktoharnesses', 'ConversationAggregate')
    HarnessRecord: Any = apps.get_model('talktoharnesses', 'HarnessRecord')
    for row in ConversationAggregate.objects.iterator():
        state = cast(dict[str, object], row.state)
        binding_value = state.get('binding')
        if not isinstance(binding_value, dict):
            continue
        binding = cast(dict[str, object], binding_value)
        if binding.get('harness_instance_id') is not None:
            continue
        configuration_value = binding.get('configuration')
        if not isinstance(configuration_value, dict):
            continue
        configuration = cast(dict[str, object], configuration_value)
        matches: list[object] = list(
            HarnessRecord.objects.filter(
                owner_id=row.owner_id,
                kind=binding.get('kind'),
                configuration=configuration,
            ).values_list('harness_id', flat=True)[:2]
        )
        if len(matches) != 1:
            continue
        updated_state: dict[str, object] = dict(state)
        updated_binding: dict[str, object] = dict(binding)
        updated_binding['harness_instance_id'] = str(matches[0])
        updated_state['binding'] = updated_binding
        row.state = updated_state
        row.save(update_fields=['state'])


class Migration(migrations.Migration):

    dependencies = [
        ('talktoharnesses', '0002_activityrecord_apitoken_harnessrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRuleRecord',
            fields=[
                ('rule_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('principal_id', models.CharField(max_length=255)),
                ('decision', models.CharField(max_length=16)),
                ('scope_kind', models.CharField(max_length=32)),
                ('scope', models.JSONField()),
                ('matcher_kind', models.CharField(max_length=32)),
                ('matcher', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'talktoharnesses_approval_rule',
            },
        ),
        migrations.CreateModel(
            name='InteractionAuditRecord',
            fields=[
                ('audit_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('principal_id', models.CharField(max_length=255)),
                ('interaction_id', models.UUIDField()),
                ('conversation_id', models.UUIDField()),
                ('turn_id', models.UUIDField()),
                ('kind', models.CharField(max_length=32)),
                ('decision', models.CharField(blank=True, max_length=32, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('automatic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('provider_kind', models.CharField(blank=True, max_length=32, null=True)),
                ('provider_request_ids', models.JSONField(default=dict)),
                ('deciding_rule_id_copy', models.UUIDField(blank=True, null=True)),
                ('rule_decision', models.CharField(blank=True, max_length=16, null=True)),
                ('rule_scope', models.JSONField(blank=True, null=True)),
                ('rule_matcher', models.JSONField(blank=True, null=True)),
                ('request_action', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talktoharnesses_interaction_audit',
            },
        ),
        migrations.AddField(
            model_name='interactionanswerrecord',
            name='answer_command_suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactionanswerrecord',
            name='command',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_answer', to='talktoharnesses.commandrecord'),
        ),
        migrations.AddField(
            model_name='interactionanswerrecord',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_answers', to='talktoharnesses.conversationaggregate'),
        ),
        migrations.AddField(
            model_name='interactionanswerrecord',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactionanswerrecord',
            name='resolution_event_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='policy_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='provider_correlation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='request_event_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['status', 'policy_evaluated_at'], name='tth_interaction_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrulerecord',
            index=models.Index(fields=['principal_id', 'scope_kind'], name='tth_rule_principal_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrulerecord',
            index=models.Index(fields=['principal_id', '-created_at', '-rule_id'], name='tth_rule_page_idx'),
        ),
        migrations.AddField(
            model_name='interactionauditrecord',
            name='deciding_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='talktoharnesses.approvalrulerecord'),
        ),
        migrations.AddIndex(
            model_name='interactionauditrecord',
            index=models.Index(fields=['principal_id', '-created_at', '-audit_id'], name='tth_audit_page_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionauditrecord',
            index=models.Index(fields=['interaction_id'], name='tth_audit_interaction_idx'),
        ),
        migrations.RunPython(backfill_harness_instance_ids, migrations.RunPython.noop),
    ]
