# Generated by Django 5.2.17 on 2026-08-08 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talktoharnesses', '0003_phase6_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandrecord',
            name='target_turn_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationeventrecord',
            name='turn_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='order_index',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConversationBindingRecord',
            fields=[
                ('binding_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('configuration', models.JSONField()),
                ('harness_instance_id', models.UUIDField(blank=True, null=True)),
                ('native_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('launch_snapshot', models.JSONField(blank=True, null=True)),
                ('requires_session_recreation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talktoharnesses.conversationaggregate')),
            ],
            options={
                'db_table': 'talktoharnesses_binding',
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='tth_binding_history_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('conversation',), name='tth_one_active_binding')],
            },
        ),
    ]
